version: "2"

run:
  timeout: 3m
  tests: true

output:
  formats:
    text:
      path: stdout
      colors: true

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errcheck
    - misspell
  settings:
    misspell:
      locale: US
  exclusions:
    # Treat generated code leniently
    generated: lax
    # Per-linter/path patterns to quiet expected cases
    rules:
      - linters: [errcheck]
        source: ^\s*defer\s+
      - linters: [errcheck]
        path: _test\.go
      - linters: [errcheck]
        path: .*_generated\.go
    # Paths to exclude from linting
    paths:
      - vendor$
      - dist$
      - third_party$
      - builtin$
      - examples$
      - ^\.github/
      - ^\.git/

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/N-Hoque/static-file-server
  exclusions:
    generated: lax
    paths:
      - vendor$
      - dist$
      - third_party$
      - builtin$
      - examples$
      - ^\.github/
      - ^\.git/
      - .*_generated\.go
