load("@gazelle//:def.bzl", "gazelle")
load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_push")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

gazelle(name = "gazelle")

go_binary(
    name = "serve",
    embed = [":static-file-server_lib"],
    visibility = ["//visibility:public"],
)

pkg_tar(
    name = "serve_layer",
    srcs = [":serve"],
    mode = "0755",
    package_dir = "/",
)

oci_image(
    name = "serve_image",
    base = "@distroless_base",
    entrypoint = ["/serve"],
    tars = [":serve_layer"],
    # Optionally set architecture here, or rely on --platforms during build.
    # architecture = "amd64",
)

oci_push(
    name = "push",
    image = ":serve_image",
    remote_tags = ["{STABLE_DOCKER_TAG}"],
    # Resolved at runtime via --stamp + workspace_status_command.
    repository = "{STABLE_DOCKER_IMAGE}",
)

go_library(
    name = "static-file-server_lib",
    srcs = ["main.go"],
    importpath = "github.com/N-Hoque/static-file-server",
    visibility = ["//visibility:private"],
    deps = ["//pkg/cli"],
)
