"""MODULE.bazel"""

module(name = "static-file-server")  # any name

# Core deps
bazel_dep(name = "rules_go", version = "0.57.0")
bazel_dep(name = "gazelle", version = "0.45.0")
bazel_dep(name = "rules_pkg", version = "1.1.0")
bazel_dep(name = "rules_oci", version = "2.2.6")

# (Optional but recommended) Pin the Go toolchain version used by Bazel.
# If you omit this, rules_go will auto-download a recent supported SDK.
go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.25.1")  # current stable as of Sep 2025
go_sdk.host()  # register the host-compatible toolchain

# (Optional) Have Gazelle manage external Go deps from go.mod with Bzlmod.
# If your repo already has a go.mod at //:go.mod, this is enough.
go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
use_repo(go_deps, "in_gopkg_yaml_v3")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

oci.pull(
    name = "distroless_base",
    digest = "sha256:61e3d3df3b7a1a811ca81778ded8286f60d403c127e1b7d2176c348e822e461a",
    image = "gcr.io/distroless/base",
    platforms = [
        "linux/amd64",
        "linux/arm64/v7",
        "linux/arm64/v8",
    ],
)
use_repo(oci, "distroless_base", "distroless_base_linux_amd64", "distroless_base_linux_arm64_v7", "distroless_base_linux_arm64_v8")
