load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cli",
    srcs = [
        "args.go",
        "execute.go",
    ],
    importpath = "github.com/N-Hoque/static-file-server/pkg/cli",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/cli/help",
        "//pkg/cli/server",
        "//pkg/cli/version",
        "//pkg/config",
    ],
)

go_test(
    name = "cli_test",
    srcs = [
        "args_test.go",
        "execute_test.go",
    ],
    embed = [":cli"],
    deps = ["//pkg/config"],
)
