load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "handle",
    srcs = ["handle.go"],
    importpath = "github.com/N-Hoque/static-file-server/pkg/handle",
    visibility = ["//visibility:public"],
)

go_test(
    name = "handle_test",
    srcs = ["handle_test.go"],
    embed = [":handle"],
)
