load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "server",
    srcs = ["server.go"],
    importpath = "github.com/N-Hoque/static-file-server/pkg/cli/server",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/config",
        "//pkg/handle",
    ],
)

go_test(
    name = "server_test",
    srcs = ["server_test.go"],
    embed = [":server"],
    deps = [
        "//pkg/config",
        "//pkg/handle",
    ],
)
