name: CI
on:
  pull_request:
  workflow_call:
    outputs:
      did_build:
        description: "Whether a build artifact was produced"
        value: ${{ jobs.build.outputs.built || 'false' }}

jobs:
  check:
    name: Check for changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: file-changes
        with:
          filters: |
            go:
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'

  lint:
    name: Lint (golangci-lint)
    needs: [check]
    if: ${{ needs.check.outputs.go == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest # or 'latest' to always use newest
          args: --timeout=5m

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: [check]
    if: ${{ needs.check.outputs.go == 'true' }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true
          cache: true
      - name: Run coverage
        run: go test -cover ./...
        continue-on-error: true

  test:
    name: Test (unit tests)
    runs-on: ubuntu-latest
    needs: [check]
    if: ${{ needs.check.outputs.go == 'true' }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true
          cache: true
      - name: Run tests
        run: go test -race -count=1 ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    outputs:
      built: ${{ steps.flag.outputs.built }}
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true
          cache: true
      - name: Compile
        env:
          APP: static-file-server
          CGO_ENABLED: 0
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        shell: bash
        run: |
          EXT=""
          [ "${{ matrix.goos }}" = "windows" ] && EXT=".exe"
          mkdir -p dist
          go build -trimpath -o "dist/${APP}_${{ matrix.goos }}_${{ matrix.goarch }}${EXT}" .
      - name: Mark workflow as built
        id: flag
        run: echo "built=true" >> "$GITHUB_OUTPUT"
