name: Bump Go Version (stable)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # Mondays 06:00 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # 1) Install latest STABLE Go on the runner
      - name: Setup Go (stable)
        id: setup
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true

      # 2) Read installed Go version (from runner)
      - name: Determine installed Go version
        id: ver
        shell: bash
        run: |
          set -euo pipefail
          gv=$(go version | awk '{print $3}')   # e.g. go1.25.4
          full="${gv#go}"                       # 1.25.4
          minor="$(echo "$full" | cut -d. -f1-2)"  # 1.25
          echo "full=$full"   >> "$GITHUB_OUTPUT"
          echo "minor=$minor" >> "$GITHUB_OUTPUT"

      # 3) Modify go.mod to use that version of Go
      - name: Read current go.mod 'go' directive
        id: cur
        shell: bash
        run: |
          set -euo pipefail
          cur=$(grep -E '^go [0-9]+\.[0-9]+' go.mod | awk '{print $2}' || true)
          echo "minor=${cur:-}" >> "$GITHUB_OUTPUT"

      - name: Update go.mod 'go' directive (if needed)
        if: steps.cur.outputs.full != steps.ver.outputs.full
        shell: bash
        run: |
          set -euo pipefail
          if grep -qE '^go [0-9]+\.[0-9]+' go.mod; then
            sed -i -E "s/^go [0-9]+\.[0-9]+/go ${{ steps.ver.outputs.full }}/" go.mod
          else
            printf "go %s\n\n%s" "${{ steps.ver.outputs.full }}" "$(cat go.mod)" > go.mod
          fi
          # Remove any explicit toolchain line to avoid auto-download mismatch
          sed -i -E '/^toolchain go[0-9]+\.[0-9]+(\.[0-9]+)?/d' go.mod

      # 4) Run `go mod tidy` (no -compat needed)
      - name: Tidy
        if: steps.cur.outputs.full != steps.ver.outputs.full
        shell: bash
        run: go mod tidy

      # 5) Create a PR only if versions differ / changes exist
      - name: Create PR
        if: steps.cur.outputs.full != steps.ver.outputs.full
        uses: peter-evans/create-pull-request@v7
        with:
          branch: chore/bump-go-stable-${{ steps.ver.outputs.full }}
          title: "chore: bump Go to stable ${{ steps.ver.outputs.full }}"
          draft: true
          commit-message: "chore: bump Go to stable ${{ steps.ver.outputs.full }}"
          body: |
            Align `go.mod` with the latest **stable** Go toolchain detected on the runner.

            - `go.mod go` → `${{ steps.ver.outputs.full }}`
            - Removed any `toolchain goX.Y[.Z]` line to avoid auto-download mismatches
          add-paths: |
            go.mod
            go.sum
