name: Docker Hub Publish (Linux)

on:
  push:
    branches: ["master-nhoque"]
    tags: ["v*.*.*"]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: "Push Image"
    needs: [build]
    if: ${{ needs.build.outputs.did_build == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Create Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_IMAGE }}
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/heads/master') }}
            type=ref,event=tag
            type=sha,format=long

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          provenance: false
          sbom: false
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ vars.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ vars.DOCKER_IMAGE }}:buildcache,mode=max
