name: Docker Hub Publish (Linux)

on:
  push:
    branches: ["master-nhoque"]
    tags: ["v*.*.*"]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  linux:
    name: Build & Push (linux/amd64, linux/arm64)
    runs-on: ubuntu-latest
    environment: "Push Image"
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_REPOSITORY }}
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/heads/master') }}
            type=ref,event=tag
            type=sha,format=long

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          provenance: false
          sbom: false
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE }}:buildcache,mode=max
